[[bin]]
name = "leetcode"
path = "src/bin/leetcode.rs"

[package]
name = "leetcode-cli"
version = "0.1.4"
authors = ["clearloop <udtrokia@163.com>"]
edition = "2018"
description = "Leet your code in command-line."
repository = "https://github.com/clearloop/leetcode-cli"
license = "MIT"
documentation = "https://docs.rs/leetcode_cli"
homepage = "https://github.com/clearloop/leetcode-cli"
keywords = ["games"]
readme = './README.md'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
app_dirs = "1.2.1"
clap = "2.33.0"
colored = "1.9.1"
diesel = { version = "1.4.3", features = ["sqlite"]}
dirs = "2.0.2"
env_logger = "0.7.1"
keyring = "0.7.1"
log = "0.4"
openssl = "0.10.26"
reqwest = "0.9.24"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.44"
toml = "0.5.5"