[[bin]]
name = "lc"
path = "src/bin/lc.rs"

[package]
name = "lc"
version = "0.1.0"
authors = ["clearloop <udtrokia@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "2.0.2"
sled = "0.30.3"
colored = "1.9.0"
reqwest = "0.9.24"